apiVersion: apps/v1
kind: Deployment
metadata:
  name: userlogin-deployment1
spec:
  selector:
    matchLabels:
      app: userlogin
  replicas: 2
  template:
    metadata:
      labels:
        app: userlogin
    spec:
      containers:
      - name: userlogin
        image: kingslayerr/teamproject:version2
        ports:
        - containerPort: 5000
